import 'dart:convert';
import 'package:ketion/core/services/file_picker_service.dart';
import 'package:ketion/features/blocks/domain/usecases/create_block_usecase.dart';
import 'package:ketion/features/editor/domain/models/block_data_models.dart';
import 'package:ketion/features/pages/domain/usecases/create_page_usecase.dart';

class ImportService {
  final CreatePageUseCase _createPageUseCase;
  final CreateBlockUseCase _createBlockUseCase;
  final FilePickerService _filePickerService;

  ImportService(this._createPageUseCase, this._createBlockUseCase,
      this._filePickerService);

  Future<void> importMarkdownFile() async {
    final result = await _filePickerService.pickFiles(
      allowedExtensions: ['md', 'txt'],
    );

    if (result.isEmpty) {
      return; // User canceled
    }

    await importMarkdownFromBytes(result.first.name, result.first.bytes);
  }

  Future<void> importMarkdownFromBytes(String fileName, List<int> bytes) async {
    final title = fileName.replaceAll(RegExp(r'\.md$|\.txt$'), '');
    final content = utf8.decode(bytes);
    final lines = const LineSplitter().convert(content);

    // 1. Create page
    final pageResult = await _createPageUseCase(title: title);
    if (pageResult.isError) return;

    final pageId = pageResult.asValue!.value.id;

    // 2. Parse lines and create blocks
    double position = 0;

    for (final line in lines) {
      if (line.trim().isEmpty) continue; // skip empty lines for MVP

      final blockData = _parseLineToBlockData(line);
      final json = blockData.toJson();

      // Need to include runtimeType so fromJson works when reading from DB
      // The toJson method generated by Freezed includes 'runtimeType' key
      final type = json['runtimeType'] as String? ?? 'unknown';
      final dataStr = jsonEncode(json);

      await _createBlockUseCase(
        pageId: pageId,
        type: type,
        position: position,
        data: dataStr,
      );
      position += 1000.0;
    }
  }

  BlockDataModel _parseLineToBlockData(String line) {
    // Check for headings
    final headingMatch = RegExp(r'^(#{1,6})\s+(.*)$').firstMatch(line);
    if (headingMatch != null) {
      return BlockDataModel.text(
        headingLevel: headingMatch.group(1)!.length,
        spans: [_parseSpan(headingMatch.group(2)!)],
      );
    }

    // Check for unordered lists
    final listMatch = RegExp(r'^[-*+]\s+(.*)$').firstMatch(line);
    if (listMatch != null) {
      return BlockDataModel.list(
        listType: 'bullet',
        spans: [_parseSpan(listMatch.group(1)!)],
      );
    }

    // Check for checklist
    final checklistMatch =
        RegExp(r'^[-*+]\s+\[([ xX])\]\s+(.*)$').firstMatch(line);
    if (checklistMatch != null) {
      final checked = checklistMatch.group(1)!.toLowerCase() == 'x';
      return BlockDataModel.list(
        listType: 'checklist',
        checked: checked,
        spans: [_parseSpan(checklistMatch.group(2)!)],
      );
    }

    // Check for images
    final imageMatch = RegExp(r'^!\[([^\]]*)\]\((.*?)\)$').firstMatch(line);
    if (imageMatch != null) {
      return BlockDataModel.image(
        caption: imageMatch.group(1),
        attachmentId: imageMatch.group(2)!,
      );
    }

    // Check for links (simplified file import)
    final fileMatch = RegExp(r'^\[([^\]]+)\]\((.*?)\)$').firstMatch(line);
    if (fileMatch != null) {
      return BlockDataModel.file(
        caption: fileMatch.group(1),
        attachmentId: fileMatch.group(2)!,
      );
    }

    // Fallback to text paragraph
    return BlockDataModel.text(
      headingLevel: 0,
      spans: [_parseSpan(line)],
    );
  }

  TextSpanData _parseSpan(String text) {
    // For MVP, simple parsing without nested inline styles
    // In a real app we'd parse markdown AST
    return TextSpanData(text: text);
  }
}
